function names = namesOfControlCases_load(excludeTheseSentences)

	if nargin < 1
		excludeTheseSentences = 5:5:20;
	end

	whichSentences = 1:20;
	whichSentences = setdiff(whichSentences,excludeTheseSentences);

	names = {};
	for ii = whichSentences
		numChars = sprintf('%02.0f',ii);
		names = [names; ...
			{['sp' numChars '_babble_sn5']; ...
			['sp' numChars '_babble_sn10']; ...
			['sp' numChars '_car_sn5']; ...
			['sp' numChars '_car_sn10']; ...
			['sp' numChars '_street_sn5']; ...
			['sp' numChars '_street_sn10']; ...
			['sp' numChars '_train_sn5']; ...
			['sp' numChars '_train_sn10']}];
	end
end
